// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1login', async function() {
    await driver.get("http://petromiles-frontend.herokuapp.com/")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.id("input-27")).click()
    await driver.findElement(By.id("input-27")).sendKeys("miguele.coccaro@gmail.com")
    await driver.findElement(By.id("password")).click()
    {
      const element = await driver.findElement(By.css(".theme--dark > .v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("password")).sendKeys("clave1234")
    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    {
      const element = await driver.findElement(By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(4) .v-list-item__title:nth-child(1)")).click()
  })
})
