// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('2comprapuntos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('2comprapuntos', async function() {
    await driver.get("http://petromiles-frontend.herokuapp.com/buy-points")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.id("input-58")).click()
    await driver.findElement(By.id("input-58")).sendKeys("4000")
    await driver.findElement(By.css(".v-select__selections")).click()
    await driver.findElement(By.id("list-item-95-1")).click()
    await driver.findElement(By.css(".col .v-btn__content")).click()
    {
      const element = await driver.findElement(By.css(".col .v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".success > .v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".success > .v-btn__content")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".v-btn--router > .v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".v-btn--router > .v-btn__content")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(1) .v-btn .v-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(1) .v-btn .v-icon")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
